!***************************************************************************************************
!- PURPORSE:
!  DEFINE VARIABLES USED IN SOLUTION PROCEDURES
!
!- TYPES
!  SOLUTION, INSTRUCTION_NODE, INSTRUCTION_LIST, NODE_DOF, NODE_VALUE, BND_NODE, BND_LINE
!  
!- GLOABLE VARIABLES:
!  SOLUTION_TYPE, INSTRUCTIONS, NUM_DISP_EQUATION, NUM_GIVEN_DISP, NUM_NODAL_FORCE, NUM_LINE_FORCE
!  NODE_DISP_DOF, DISPLACEMENT, NODAL_STRAIN, NODAL_STRESS, INTE_STRAIN, INTE_STRESS, GIVEN_DISP
!  NODAL_FORCE, LINE_FORCE, ELE_FORCE, FORCE, STIFFNESS, DIAGONAL, LINE_SHAPE2, LINE_SHAPE3
!  LINE_DSHAPE2, LINE_DSHAPE3, START_TIME, END_TIME, START_CLK, END_CLK
!  
!- PROGAMMED BY:
!  ZHIHAI XIANG, DEPARTMENT OF ENGINEERING MECHANICS, TSINGHUA UNIVERSITY, NOVEMBER 1, 2015
!***************************************************************************************************

MODULE SOLUTION_DATA

USE BASIC_DATA

IMPLICIT NONE
            
!-- TYPES USED IN SOLUTION PROCEDURES --
! SOLUTION TYPE
TYPE SOLUTION
   LOGICAL(LG_KIND):: MECHANICAL = .FALSE.
   LOGICAL(LG_KIND):: THERMAL    = .FALSE.
END TYPE

! MACRO LIST NODE
TYPE INSTRUCTION_NODE
   CHARACTER(WORD_KIND):: INSTRUCTION = ' '
   CHARACTER(WORD_KIND):: OPTION(NUM_OPT)
   TYPE(INSTRUCTION_NODE), POINTER:: PRE  => NULL()
   TYPE(INSTRUCTION_NODE), POINTER:: NEXT => NULL()
END TYPE

! MACRO LIST HEAD
TYPE INSTRUCTION_LIST
   TYPE(INSTRUCTION_NODE), POINTER:: HEAD => NULL()   
   TYPE(INSTRUCTION_NODE), POINTER:: TAIL => NULL()   
END TYPE

! MAPPING FROM NODE TO DEGREE-OF-FREEDOMS
TYPE NODE_DOF
   INTEGER(INT_KIND)                NUM_DOF  ! THE NUMBER OF DOFS AT THIS NODE
   INTEGER(INT_KIND), ALLOCATABLE:: DOFS(:)  ! THE DOFS OF THIS NODE EG. 1 2 3 4...
END TYPE

! VALUES AT ELEMENT NODES OR INTEGRATION POINTS
TYPE NODE_VALUE
   REAL(REAL_KIND), ALLOCATABLE:: VALUE(:)
END TYPE

! GIVEN NODAL BOUNDARY CONDITION
TYPE BND_NODE
   INTEGER(INT_KIND)               NODE      ! THE NODE NUMBER
   LOGICAL(LG_KIND), ALLOCATABLE:: GIVEN(:)  ! IF THERE IS A GIVEN VALUE AT THIS DOF
   REAL(REAL_KIND), ALLOCATABLE::  VALUE(:)  ! GIVEN VALUES
END TYPE

! GIVEN LINE BOUNDARY FORCE
TYPE BND_LINE
   INTEGER(INT_KIND) ELEMENT        ! THE ELEMENT NUMBER
   INTEGER(INT_KIND) NODE(3)        ! NODES ON A LINE
   REAL(REAL_KIND)   TRACTION(2,3)  ! GIVEN NORMAL AND TANGENT TRACTIONS ON NODE(1) TO NODE(3)
END TYPE

!-- GLOABLE VARIABLES --
TYPE(SOLUTION) SOLUTION_TYPE                    ! SOLUTION TYPE
TYPE(INSTRUCTION_LIST) INSTRUCTIONS             ! SOLUTION INSTRUCTIONS

INTEGER(INT_KIND) NUM_DISP_EQUATION             ! THE TOTAL NUMBER OF DISPLACEMENT EQUATIONS
INTEGER(INT_KIND) NUM_GIVEN_DISP                ! THE TOTAL NUMBER OF GIVEN DISPLACEMENTS
INTEGER(INT_KIND) NUM_NODAL_FORCE               ! THE TOTAL NUMBER OF GIVEN NODAL FORCES
INTEGER(INT_KIND) NUM_LINE_FORCE                ! THE TOTAL NUMBER OF GIVEN LINE FORCES

TYPE(NODE_DOF), ALLOCATABLE:: NODE_DISP_DOF(:)  ! DISPLACEMENT DOFS FOR EACH NODE

! STATUS VARIABLES
REAL(REAL_KIND), ALLOCATABLE::  DISPLACEMENT(:) ! DISPLACEMENTS
TYPE(NODE_VALUE), ALLOCATABLE:: NODAL_STRAIN(:) ! STRAINS AT NODAL POINTS
TYPE(NODE_VALUE), ALLOCATABLE:: NODAL_STRESS(:) ! STRESS AT NODAL POINTS
TYPE(NODE_VALUE), ALLOCATABLE:: INTE_STRAIN(:)  ! STRAINS AT INTEGRATION POINTS
TYPE(NODE_VALUE), ALLOCATABLE:: INTE_STRESS(:)  ! STRESS AT INTEGRATION POINTS

! BOUNDARY CONDITION
TYPE(BND_NODE), ALLOCATABLE:: GIVEN_DISP(:)     ! GIVEN DISPLACEMENTS
TYPE(BND_NODE), ALLOCATABLE:: NODAL_FORCE(:)    ! GIVEN NODAL FORCES
TYPE(BND_LINE), ALLOCATABLE:: LINE_FORCE(:)     ! GIVEN LINE FORCES
TYPE(NODE_VALUE), ALLOCATABLE:: ELE_FORCE(:)    ! ELEMENT LOAD VECTOR
REAL(REAL_KIND), ALLOCATABLE::  FORCE(:)        ! GLOABLE LOAD VECTOR

! VARIABLES FOR DIRECT ANALYSIS
REAL(REAL_KIND), ALLOCATABLE::   STIFFNESS(:)   ! GLOBAL STIFFNESS MATRIX (SPARSE, VARIABLE BANDWIDTH)
INTEGER(INT_KIND), ALLOCATABLE:: DIAGONAL(:)    ! THE POSITION OF THE DIAGONAL ELEMENT IN STIFFNESS VECTOR

! SHAPE FUNCTIONS FOR CALCULATING LINE LOAD
REAL(REAL_KIND) LINE_SHAPE2(2,2)
REAL(REAL_KIND) LINE_SHAPE3(3,3)

! DERIVATIVE OF SHAPE FUNCTIONS FOR CALCULATING LINE LOAD
REAL(REAL_KIND) LINE_DSHAPE2(2,2)
REAL(REAL_KIND) LINE_DSHAPE3(3,3)

! SOLUTION TIME STATISTICS
INTEGER(INT_KIND) START_TIME(8) ! THE START TIME OF THE PROGRAM
INTEGER(INT_KIND) END_TIME(8)   ! THE END TIME OF THE PROGRAM
INTEGER(INT_KIND) START_CLK     ! THE START CLOCK OF THE PROGRAM
INTEGER(INT_KIND) END_CLK       ! THE END CLOCK OF THE PROGRAM

END MODULE SOLUTION_DATA