!***************************************************************************************************
!- PURPORSE:
!     BRANCH TO DIFFERENT SUBROUTINE TO GET ELEMENT STIFFNESS MATRIX.
!  
!- INPUT ARGUMENTS:
!  OPTION: THE OPTIONS OF SOLUTION TYPES
!
!- OUTPUT ARGUMENTS:
!  NONE
!
!- CALL PROCEDURES:
!  MODULE PROCEDURE:   ERROR
!  EXTERNAL PROCEDURE: STIFFNESS_PLANE
!
!- CALLED BY
!  SOLVER_MANAGER
!
!- PROGAMMED BY:
!  ZHIHAI XIANG, DEPARTMENT OF ENGINEERING MECHANICS, TSINGHUA UNIVERSITY, NOVEMBER 1, 2015
!***************************************************************************************************

SUBROUTINE STIFFNESS(OPTION)

USE SOLUTION_DATA, ONLY: INT_KIND, WORD_KIND, NUM_OPT, NUM_ELEMENT, ELEMENT_LIB, ELEMENTS, ERROR

IMPLICIT NONE

CHARACTER(WORD_KIND), INTENT(IN):: OPTION(NUM_OPT) ! THE OPTIONS OF SOLUTION TYPES
INTEGER(INT_KIND)                  I_ELEMENT       ! LOOP INDEX

!-- CALCULATE STIFFNESS MATRIX FOR EACH ELEMENT --
DO I_ELEMENT = 1, NUM_ELEMENT
   SELECT CASE(TRIM(ELEMENT_LIB(ELEMENTS(I_ELEMENT)%ELEMENT)%ELEMENT_TYPE))
      CASE ('TRIANGLE3', 'TRIANGLE6', 'RECTANGLE4', 'RECTANGLE8', 'RECTANGLE9')
         CALL STIFFNESS_PLANE(I_ELEMENT, ELEMENT_LIB(ELEMENTS(I_ELEMENT)%ELEMENT)%NUM_NODE, OPTION)
      
      CASE DEFAULT
         CALL ERROR('Invalid element type (' // TRIM(ELEMENT_LIB(ELEMENTS(I_ELEMENT)%ELEMENT)%ELEMENT_TYPE) // ') in STIFFNESS!')
   END SELECT
ENDDO

END SUBROUTINE STIFFNESS