!***************************************************************************************************
!- PURPORSE:
!     CLEAR THE INSTRUCTION LIST AND MEASUREMENTS AFTER A SOLUTION STEP BLOCK.
!  
!- INPUT ARGUMENTS:
!  NONE
!
!- OUTPUT ARGUMENTS:
!  NONE
!
!- CALL PROCEDURES:
!  NONE
!
!- CALLED BY:
!  SOLVER_MANAGER  
!
!- PROGAMMED BY:
!  ZHIHAI XIANG, DEPARTMENT OF ENGINEERING MECHANICS, TSINGHUA UNIVERSITY, SEPTEMBER 12, 2007
!***************************************************************************************************

SUBROUTINE CLEAR_INSTRUCTION

USE SOLUTION_DATA, ONLY: INSTRUCTION_NODE, INSTRUCTIONS

IMPLICIT NONE

TYPE(INSTRUCTION_NODE), POINTER:: P_INSTRUCTION

!-- CLEAR INSTRUCTION LIST --
DO WHILE(ASSOCIATED(INSTRUCTIONS%HEAD))
   P_INSTRUCTION => INSTRUCTIONS%HEAD%NEXT
   DEALLOCATE(INSTRUCTIONS%HEAD)
   INSTRUCTIONS%HEAD => P_INSTRUCTION
ENDDO

END SUBROUTINE CLEAR_INSTRUCTION