!***************************************************************************************************
!- PURPORSE:
!     CLEAR ALL ALLOCATED SPACES AND CALCULATE THE TIME STATISTIC.
!  
!- INPUT ARGUMENTS:
!  NONE
!
!- OUTPUT ARGUMENTS:
!  NONE
!
!- CALL PROCEDURES:
!  NONE
!
!- CALLED BY:
!  FEMT
!
!- PROGAMMED BY:
!  ZHIHAI XIANG, DEPARTMENT OF ENGINEERING MECHANICS, TSINGHUA UNIVERSITY, JANUARY 18, 2016
!***************************************************************************************************

SUBROUTINE SUMMARY

USE SOLUTION_DATA
USE IFPORT

IMPLICIT NONE

INTEGER(INT_KIND) I          !  LOOP INDEX
INTEGER(INT_KIND) TIME_DIF   ! THE TIME SPAN
INTEGER(INT_KIND) COUNT_RATE ! THE NUMBER OF CLICKS PER SECOND

!-- GET THE CURRENT TIME --
CALL DATE_AND_TIME (VALUES = END_TIME)
CALL SYSTEM_CLOCK(END_CLK, COUNT_RATE)

!-- OUT THE TIME STATISTIC --
WRITE(*,*)
WRITE(*,"('PROGRAM STARTED AT   : ', I4.4, '/', I2.2, '/', I2.2, ', ', 2(I2.2, ':'), I2.2)")&
   (START_TIME(I), I = 1, 3), (START_TIME(I), I = 5, 7)
WRITE(OUT,"('PROGRAM STARTED AT   : ', I4.4, '/', I2.2, '/', I2.2, ', ', 2(I2.2, ':'), I2.2)")&
   (START_TIME(I), I = 1, 3), (START_TIME(I), I = 5, 7)
WRITE(LOG,"('PROGRAM STARTED AT   : ', I4.4, '/', I2.2, '/', I2.2, ', ', 2(I2.2, ':'), I2.2)")&
   (START_TIME(I), I = 1, 3), (START_TIME(I), I = 5, 7)   
   
WRITE(*,"('PROGRAM TERMINATED AT: ', I4.4, '/', I2.2, '/', I2.2, ', ', 2(I2.2, ':'), I2.2)")&
   (END_TIME(I), I = 1, 3), (END_TIME(I), I = 5, 7)
WRITE(OUT,"('PROGRAM TERMINATED AT: ', I4.4, '/', I2.2, '/', I2.2, ', ', 2(I2.2, ':'), I2.2)")&
   (END_TIME(I), I = 1, 3), (END_TIME(I), I = 5, 7)
WRITE(LOG,"('PROGRAM TERMINATED AT: ', I4.4, '/', I2.2, '/', I2.2, ', ', 2(I2.2, ':'), I2.2)")&
   (END_TIME(I), I = 1, 3), (END_TIME(I), I = 5, 7)      
   
TIME_DIF = (END_CLK - START_CLK) / COUNT_RATE
WRITE(*,"('TOTAL ELAPSED TIME   : ', I0, ' hour ', I0, ' minutes ', I0, ' seconds.')")&
   TIME_DIF / 3600, MOD(TIME_DIF, 3600) / 60, MOD(TIME_DIF, 60)
WRITE(OUT,"('TOTAL ELAPSED TIME   : ', I0, ' hour ', I0, ' minutes ', I0, ' seconds.')")&
   TIME_DIF / 3600, MOD(TIME_DIF, 3600) / 60, MOD(TIME_DIF, 60)
WRITE(LOG,"('TOTAL ELAPSED TIME   : ', I0, ' hour ', I0, ' minutes ', I0, ' seconds.')")&
   TIME_DIF / 3600, MOD(TIME_DIF, 3600) / 60, MOD(TIME_DIF, 60)      


!-- RELEASE ALL ALLOCATED MEMORIES --
! VARIABLES IN MODULE: BASIC_DATA
DEALLOCATE(XYZ)
DEALLOCATE(MATERIALS)
IF(ALLOCATED(GEOMETRIES)) DEALLOCATE(GEOMETRIES)

DO I = 1, NUM_ELEMENT
   DEALLOCATE(ELEMENTS(I)%NODE)
ENDDO
DEALLOCATE(ELEMENTS)

DO I = 1, NUM_ELE_TYPE
   IF(ALLOCATED(ELEMENT_LIB(I)%INTE_COORD)) DEALLOCATE(ELEMENT_LIB(I)%INTE_COORD)
   IF(ALLOCATED(ELEMENT_LIB(I)%SHAPE))      DEALLOCATE(ELEMENT_LIB(I)%SHAPE)
   IF(ALLOCATED(ELEMENT_LIB(I)%DSHAPE))     DEALLOCATE(ELEMENT_LIB(I)%DSHAPE)
ENDDO

! VARIABLES IN MODULE: SOLUTION_DATA
IF(ALLOCATED(NODE_DISP_DOF)) THEN
   DO I = 1, NUM_NODE
      DEALLOCATE(NODE_DISP_DOF(I)%DOFS)
   ENDDO
   DEALLOCATE(NODE_DISP_DOF)
ENDIF

DEALLOCATE(DISPLACEMENT)

IF(ALLOCATED(NODAL_STRAIN)) THEN
   DO I = 1, NUM_NODE
      DEALLOCATE(NODAL_STRAIN(I)%VALUE)
   ENDDO
   DEALLOCATE(NODAL_STRAIN)
ENDIF

IF(ALLOCATED(NODAL_STRESS)) THEN
   DO I = 1, NUM_NODE
      DEALLOCATE(NODAL_STRESS(I)%VALUE)
   ENDDO
   DEALLOCATE(NODAL_STRESS)
ENDIF

IF(ALLOCATED(INTE_STRAIN)) THEN
   DO I = 1, NUM_ELEMENT
      DEALLOCATE(INTE_STRAIN(I)%VALUE)
   ENDDO
   DEALLOCATE(INTE_STRAIN)
ENDIF

IF(ALLOCATED(INTE_STRESS)) THEN
   DO I = 1, NUM_ELEMENT
      DEALLOCATE(INTE_STRESS(I)%VALUE)
   ENDDO
   DEALLOCATE(INTE_STRESS)
ENDIF

IF(ALLOCATED(GIVEN_DISP)) THEN
   DO I = 1, NUM_GIVEN_DISP
      DEALLOCATE(GIVEN_DISP(I)%GIVEN)
      DEALLOCATE(GIVEN_DISP(I)%VALUE)
   ENDDO
   DEALLOCATE(GIVEN_DISP)
ENDIF

IF(ALLOCATED(NODAL_FORCE)) THEN
   DO I = 1, NUM_NODAL_FORCE
      DEALLOCATE(NODAL_FORCE(I)%GIVEN)
      DEALLOCATE(NODAL_FORCE(I)%VALUE)
   ENDDO
   DEALLOCATE(NODAL_FORCE)
ENDIF

IF(ALLOCATED(LINE_FORCE)) DEALLOCATE(LINE_FORCE)

IF(ALLOCATED(ELE_FORCE)) THEN
   DO I = 1, NUM_ELEMENT
      DEALLOCATE(ELE_FORCE(I)%VALUE)
   ENDDO
   DEALLOCATE(ELE_FORCE)
ENDIF

DEALLOCATE(FORCE)

IF(ALLOCATED(STIFFNESS))  DEALLOCATE(STIFFNESS)

IF(ALLOCATED(DIAGONAL)) DEALLOCATE(DIAGONAL)

END SUBROUTINE SUMMARY