!***************************************************************************************************
!- PURPORSE:
!     INITIATE VARIABLES USED IN SOLUTION PROCESS.
!  
!- INPUT ARGUMENTS:
!  NONE
!
!- OUTPUT ARGUMENTS:
!  NONE
!
!- CALL PROCEDURES:
!  EXTERNAL PROCEDURE:    INIT_MECHANICAL, LOAD_SHAPE
!  INTRINCICAL PROCEDURE: RANDOM_SEED
!
!- CALLED BY:
!  INITIATE
!
!- PROGAMMED BY:
!  ZHIHAI XIANG, DEPARTMENT OF ENGINEERING MECHANICS, TSINGHUA UNIVERSITY, NOVEMBER 1, 2015
!***************************************************************************************************

SUBROUTINE INIT_SOLUTION

USE SOLUTION_DATA, ONLY: SOLUTION_TYPE

IMPLICIT NONE

!-- INITIATE VARIABLES FOR MECHANICAL ANALYSIS -- 
IF(SOLUTION_TYPE%MECHANICAL) CALL INIT_MECHANICAL

!-- CALCULATE SHAPE FUNCTIONS AND THEIR DERIVATIVES FOR LOAD CALCULATING
CALL LOAD_SHAPE

END SUBROUTINE INIT_SOLUTION