!***************************************************************************************************
!- PURPORSE:
!     INITIATE ELEMENT LIBRARY.
!  
!- INPUT ARGUMENTS:
!  NONE
!
!- OUTPUT ARGUMENTS:
!  NONE
!
!- CALL PROCEDURES:
!  MODULE PROCEDURE:   ERROR, NUM2STR  
!  EXTERNAL PROCEDURE: INIT_INTEGRATION, INIT_SHAPE
!
!- CALLED BY:
!  INITIATE
!
!- PROGAMMED BY:
!  ZHIHAI XIANG, DEPARTMENT OF ENGINEERING MECHANICS, TSINGHUA UNIVERSITY, NOVEMBER 1, 2015
!***************************************************************************************************

SUBROUTINE INIT_ELE_LIB

USE BASIC_DATA, ONLY: INT_KIND, NUM_ELE_TYPE, ELEMENT_LIB, ERROR, NUM2STR

IMPLICIT NONE

INTEGER(INT_KIND) I    ! ELEMENT TYPE NUMBER

!-- SET ELEMENT TYPE INFORMATION --
DO I = 1, NUM_ELE_TYPE      
   SELECT CASE (I)
      CASE (1)
         ELEMENT_LIB(I)%ELEMENT_TYPE = 'TRIANGLE3'
         ELEMENT_LIB(I)%NUM_NODE     = 3
         ELEMENT_LIB(I)%NUM_INTP     = 1
         ELEMENT_LIB(I)%DISP_DOF     = 2
         ELEMENT_LIB(I)%NUM_STIFF    = 21
               
      CASE (2)
         ELEMENT_LIB(I)%ELEMENT_TYPE = 'TRIANGLE6'
         ELEMENT_LIB(I)%NUM_NODE     = 6
         ELEMENT_LIB(I)%NUM_INTP     = 3
         ELEMENT_LIB(I)%DISP_DOF     = 2
         ELEMENT_LIB(I)%NUM_STIFF    = 78
   
      CASE (3)
         ELEMENT_LIB(I)%ELEMENT_TYPE = 'RECTANGLE4'
         ELEMENT_LIB(I)%NUM_NODE     = 4
         ELEMENT_LIB(I)%NUM_INTP     = 4
         ELEMENT_LIB(I)%DISP_DOF     = 2
         ELEMENT_LIB(I)%NUM_STIFF    = 36
 
      CASE (4)
         ELEMENT_LIB(I)%ELEMENT_TYPE = 'RECTANGLE8'
         ELEMENT_LIB(I)%NUM_NODE     = 8
         ELEMENT_LIB(I)%NUM_INTP     = 9
         ELEMENT_LIB(I)%DISP_DOF     = 2
         ELEMENT_LIB(I)%NUM_STIFF    = 136
      CASE (5)
         ELEMENT_LIB(I)%ELEMENT_TYPE = 'RECTANGLE9'
         ELEMENT_LIB(I)%NUM_NODE     = 9
         ELEMENT_LIB(I)%NUM_INTP     = 9
         ELEMENT_LIB(I)%DISP_DOF     = 2
         ELEMENT_LIB(I)%NUM_STIFF    = 171   
         
      CASE DEFAULT
         CALL ERROR(TRIM('Undefined element type number: ' // NUM2STR(I)))
                     
   END SELECT
   
   ! SET GAUSS POINT INFORMATION
   CALL INIT_INTEGRATION(ELEMENT_LIB(I))
   
   ! CALCULATE SHAPE FUNCTION AND ITS DERIVATIVES
   CALL INIT_SHAPE(ELEMENT_LIB(I))
ENDDO

END SUBROUTINE INIT_ELE_LIB