!***************************************************************************************************
!- PURPORSE:
!     CALCULATE SHAPE FUNCTIONS AND DERIVATIVE OF SHAPE FUNCTIONS FOR CALCULATING LINE AND SURFACE LOAD.
!  
!- INPUT ARGUMENTS:
!  NONE
!
!- OUTPUT ARGUMENTS:
!  NONE
!
!- CALL PROCEDURES:
!  NONE
!
!- CALLED BY
!  INIT_SOLUTION
!
!- PROGAMMED BY:
!  ZHIHAI XIANG, DEPARTMENT OF ENGINEERING MECHANICS, TSINGHUA UNIVERSITY, NOVEMBER 1, 2015
!***************************************************************************************************

SUBROUTINE LOAD_SHAPE

USE SOLUTION_DATA, ONLY: INT_KIND, GAUSS_COORD2, GAUSS_COORD3, LINE_SHAPE2, LINE_SHAPE3, LINE_DSHAPE2, LINE_DSHAPE3

IMPLICIT NONE

INTEGER(INT_KIND) I ! LOOP INDEX

!-- SHAPE FUNCTIONS --
! TWO GAUSS POINTS ON ONE LINE
DO I = 1, 2
   LINE_SHAPE2(1,I) = (1.0 + GAUSS_COORD2(I)) / 2.0
   LINE_SHAPE2(2,I) = (1.0 - GAUSS_COORD2(I)) / 2.0
ENDDO

! THREE GAUSS POINTS ON ONE LINE
DO I = 1, 3
   LINE_SHAPE3(1,I) = (GAUSS_COORD3(I) + 1.0) * GAUSS_COORD3(I) / 2.0
   LINE_SHAPE3(2,I) =  1.0 - GAUSS_COORD3(I)  * GAUSS_COORD3(I)
   LINE_SHAPE3(3,I) = (GAUSS_COORD3(I) - 1.0) * GAUSS_COORD3(I) / 2.0
ENDDO

!-- DERIVATIVE OF SHAPE FUNCTIONS --
! TWO GAUSS POINTS ON ONE LINE
DO I = 1, 2
   LINE_DSHAPE2(1,I) =  0.5
   LINE_DSHAPE2(2,I) = -0.5
ENDDO

! THREE GAUSS POINTS ON ONE LINE
DO I = 1, 3
   LINE_DSHAPE3(1,I) = (2.0 * GAUSS_COORD3(I) + 1.0) / 2.0
   LINE_DSHAPE3(2,I) = -2.0 * GAUSS_COORD3(I)
   LINE_DSHAPE3(3,I) = (2.0 * GAUSS_COORD3(I) - 1.0) / 2.0
ENDDO
        
END SUBROUTINE LOAD_SHAPE